### ISSUE TITLE
use `fervid` to transform vue3 sfc with unplugin

### ISSUE THREAD

**Issue by ErKeLost** [unplugin/unplugin-vue-fervid#1]
### Clear and concise description of the problem

hi @sxzz. I'm sorry to bother you, [fervid](https://github.com/phoenix-ru/fervid) has stabilized, basic production is available, and is currently refactoring some api of node, so I want to rewrite a `unplugin` plugin based on `fervid`. I have reached an agreement with the author of `fervid`, and he is also very Interested to do this in unplugin. Do you have any idea about this? 

### Suggested solution

fervid

### Alternative

-

### Additional context

-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
LGTM Good job
